sudo: required
services:
  - docker
before_install:
  - docker build -t react-truncate-markup .
  - docker images
script:
  - docker run -t react-truncate-markup
notifications:
  email: false
branches:
  only: master